---
#--------------------------------------------------
#                Controller Config                #
#--------------------------------------------------
#
#
SolverConfiguration:
  NX: 7
  NU: 3
  NP: 3
  N: 30
  NUM_UAVS: 1
  LBX_STATES: [-.inf, -.inf, -.inf, 10.0, -.inf, -0.5236, -0.6981]
  UBX_STATES: [ .inf,  .inf,   0.0, 40.0,  .inf,  0.5236,  0.6981]
  LBX_CONTROLS: [ 0.0, -0.5236, -0.6981]
  UBX_CONTROLS: [60.0,  0.5236,  0.6981]
#