/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int linearize_oneGround_lmpc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int linearize_oneGround_lmpc_alloc_mem(void);
int linearize_oneGround_lmpc_init_mem(int mem);
void linearize_oneGround_lmpc_free_mem(int mem);
int linearize_oneGround_lmpc_checkout(void);
void linearize_oneGround_lmpc_release(int mem);
void linearize_oneGround_lmpc_incref(void);
void linearize_oneGround_lmpc_decref(void);
casadi_int linearize_oneGround_lmpc_n_in(void);
casadi_int linearize_oneGround_lmpc_n_out(void);
casadi_real linearize_oneGround_lmpc_default_in(casadi_int i);
const char* linearize_oneGround_lmpc_name_in(casadi_int i);
const char* linearize_oneGround_lmpc_name_out(casadi_int i);
const casadi_int* linearize_oneGround_lmpc_sparsity_in(casadi_int i);
const casadi_int* linearize_oneGround_lmpc_sparsity_out(casadi_int i);
int linearize_oneGround_lmpc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int linearize_oneGround_lmpc_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define linearize_oneGround_lmpc_SZ_ARG 14
#define linearize_oneGround_lmpc_SZ_RES 3
#define linearize_oneGround_lmpc_SZ_IW 0
#define linearize_oneGround_lmpc_SZ_W 4679
#ifdef __cplusplus
} /* extern "C" */
#endif
