/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int nmhe_oneGround(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int nmhe_oneGround_alloc_mem(void);
int nmhe_oneGround_init_mem(int mem);
void nmhe_oneGround_free_mem(int mem);
int nmhe_oneGround_checkout(void);
void nmhe_oneGround_release(int mem);
void nmhe_oneGround_incref(void);
void nmhe_oneGround_decref(void);
casadi_int nmhe_oneGround_n_in(void);
casadi_int nmhe_oneGround_n_out(void);
casadi_real nmhe_oneGround_default_in(casadi_int i);
const char* nmhe_oneGround_name_in(casadi_int i);
const char* nmhe_oneGround_name_out(casadi_int i);
const casadi_int* nmhe_oneGround_sparsity_in(casadi_int i);
const casadi_int* nmhe_oneGround_sparsity_out(casadi_int i);
int nmhe_oneGround_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int nmhe_oneGround_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define nmhe_oneGround_SZ_ARG 12
#define nmhe_oneGround_SZ_RES 10
#define nmhe_oneGround_SZ_IW 2760
#define nmhe_oneGround_SZ_W 60836
#ifdef __cplusplus
} /* extern "C" */
#endif
