/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int nmhe_twoUavPayload(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int nmhe_twoUavPayload_alloc_mem(void);
int nmhe_twoUavPayload_init_mem(int mem);
void nmhe_twoUavPayload_free_mem(int mem);
int nmhe_twoUavPayload_checkout(void);
void nmhe_twoUavPayload_release(int mem);
void nmhe_twoUavPayload_incref(void);
void nmhe_twoUavPayload_decref(void);
casadi_int nmhe_twoUavPayload_n_in(void);
casadi_int nmhe_twoUavPayload_n_out(void);
casadi_real nmhe_twoUavPayload_default_in(casadi_int i);
const char* nmhe_twoUavPayload_name_in(casadi_int i);
const char* nmhe_twoUavPayload_name_out(casadi_int i);
const casadi_int* nmhe_twoUavPayload_sparsity_in(casadi_int i);
const casadi_int* nmhe_twoUavPayload_sparsity_out(casadi_int i);
int nmhe_twoUavPayload_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int nmhe_twoUavPayload_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define nmhe_twoUavPayload_SZ_ARG 12
#define nmhe_twoUavPayload_SZ_RES 10
#define nmhe_twoUavPayload_SZ_IW 5838
#define nmhe_twoUavPayload_SZ_W 218767
#ifdef __cplusplus
} /* extern "C" */
#endif
